export const MESSAGES_404 = [
	"Oops! Looks like you've wandered off the path of wisdom. Try again when you're feeling a bit more... accurate.",
	"The page you're looking for is so secret, even we don't know where it is.",
	"You must have taken a wrong turn at Awesome Town because this ain't it.",
	"This page left. It was tired of your indecision.",
	"If this was a treasure map, you’d be standing in the ocean.",
	"Oh, you wanted something here? Too bad, we’re fresh out of that.",
	"Well, this is awkward... the page is missing. Probably off on an adventure.",
	"This is not the page you’re looking for. Jedi mind tricks in action.",
	"Looks like we misplaced this page. Our bad!",
	"The page you're seeking took a coffee break. Try again later.",
	"This page didn’t make the cut. We had to let it go.",
	"Hmm, the page has gone poof! Like magic. But less cool.",
	"Page not found! Maybe try turning it off and on again?",
	"Well, this page flew the coop. We’ll catch it eventually!",
	"The page you’re looking for must be hiding... in the last place you’d expect.",
	"This page is playing hide and seek. It’s winning.",
	"The page you wanted is now a figment of your imagination.",
	"We didn’t lose the page, it just wandered off on its own.",
	"No page here, but plenty of room for your imagination!",
	"This page got bored and left. We don't blame it.",
];
