services:
    redis:
        image: redis:alpine
        volumes:
            - redis-data:/data
        networks:
            - base-network
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            interval: 30s
            timeout: 10s
            retries: 5

    app:
        build:
            context: ../../
            dockerfile: ./apps/web/Dockerfile
        ports:
            - "8765:8765"
        env_file:
            - .env
        depends_on:
            - redis
        networks:
            - base-network
        healthcheck:
            test: ["CMD", "curl", "-f", "http://app:8765/api/health"]
            interval: 30s
            timeout: 10s
            retries: 5
volumes:
    redis-data:

networks:
    base-network:
        driver: bridge
