services:
    cache:
        image: redis:alpine
        ports:
            - "6379:6379"
    astro:
        image: ghcr.io/uses-ink/uses.ink:latest
        environment:
            - REDIS_URL=redis://cache:6379
            # - GITHUB_TOKEN=YOUR_GITHUB_TOKEN
        ports:
            - "8765:8765"
