import { hexToRgb } from "../utils";

export default {
	dracula: {
		css: {
			"--tw-prose-body": "#282a36",
			"--tw-prose-headings": "#1a1b23",
			"--tw-prose-lead": "#44475a",
			"--tw-prose-links": "#8be9fd",
			"--tw-prose-bold": "#1a1b23",
			"--tw-prose-counters": "#6272a4",
			"--tw-prose-bullets": "#bd93f9",
			"--tw-prose-hr": "#f8f8f2",
			"--tw-prose-quotes": "#1a1b23",
			"--tw-prose-quote-borders": "#f8f8f2",
			"--tw-prose-captions": "#6272a4",
			"--tw-prose-kbd": "#1a1b23",
			"--tw-prose-kbd-shadows": hexToRgb("#1a1b23"),
			"--tw-prose-code": "#ff79c6",
			"--tw-prose-pre-code": "#f8f8f2",
			"--tw-prose-pre-bg": "#282a36",
			"--tw-prose-th-borders": "#bd93f9",
			"--tw-prose-td-borders": "#f8f8f2",

			"--tw-prose-invert-body": "#f8f8f2",
			"--tw-prose-invert-headings": "#ffffff",
			"--tw-prose-invert-lead": "#f1f2f8",
			"--tw-prose-invert-links": "#8be9fd",
			"--tw-prose-invert-bold": "#ffffff",
			"--tw-prose-invert-counters": "#bd93f9",
			"--tw-prose-invert-bullets": "#6272a4",
			"--tw-prose-invert-hr": "#44475a",
			"--tw-prose-invert-quotes": "#ffffff",
			"--tw-prose-invert-quote-borders": "#44475a",
			"--tw-prose-invert-captions": "#bd93f9",
			"--tw-prose-invert-kbd": "#ffffff",
			"--tw-prose-invert-kbd-shadows": hexToRgb("#ffffff"),
			"--tw-prose-invert-code": "#ff79c6",
			"--tw-prose-invert-pre-code": "#f8f8f2",
			"--tw-prose-invert-pre-bg": "rgb(40 42 54 / 50%)",
			"--tw-prose-invert-th-borders": "#6272a4",
			"--tw-prose-invert-td-borders": "#44475a",
		},
	},
};
