import { hexToRgb } from "../utils";

export default {
	nord: {
		css: {
			"--tw-prose-body": "#4c566a",
			"--tw-prose-headings": "#2e3440",
			"--tw-prose-lead": "#434c5e",
			"--tw-prose-links": "#5e81ac",
			"--tw-prose-bold": "#2e3440",
			"--tw-prose-counters": "#4c566a",
			"--tw-prose-bullets": "#d8dee9",
			"--tw-prose-hr": "#e5e9f0",
			"--tw-prose-quotes": "#2e3440",
			"--tw-prose-quote-borders": "#e5e9f0",
			"--tw-prose-captions": "#4c566a",
			"--tw-prose-kbd": "#2e3440",
			"--tw-prose-kbd-shadows": hexToRgb("#2e3440"),
			"--tw-prose-code": "#bf616a",
			"--tw-prose-pre-code": "#eceff4",
			"--tw-prose-pre-bg": "#3b4252",
			"--tw-prose-th-borders": "#d8dee9",
			"--tw-prose-td-borders": "#e5e9f0",

			"--tw-prose-invert-body": "#d8dee9",
			"--tw-prose-invert-headings": "#eceff4",
			"--tw-prose-invert-lead": "#e5e9f0",
			"--tw-prose-invert-links": "#88c0d0",
			"--tw-prose-invert-bold": "#eceff4",
			"--tw-prose-invert-counters": "#d8dee9",
			"--tw-prose-invert-bullets": "#4c566a",
			"--tw-prose-invert-hr": "#3b4252",
			"--tw-prose-invert-quotes": "#eceff4",
			"--tw-prose-invert-quote-borders": "#3b4252",
			"--tw-prose-invert-captions": "#d8dee9",
			"--tw-prose-invert-kbd": "#eceff4",
			"--tw-prose-invert-kbd-shadows": hexToRgb("#eceff4"),
			"--tw-prose-invert-code": "#bf616a",
			"--tw-prose-invert-pre-code": "#d8dee9",
			"--tw-prose-invert-pre-bg": "rgb(46 52 64 / 50%)",
			"--tw-prose-invert-th-borders": "#4c566a",
			"--tw-prose-invert-td-borders": "#3b4252",
		},
	},
};
